[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "v0.101.0"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"  
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()"

[[redirects]]
from = "/npmjs/*"
to = "/npmjs/"
status = 200